//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Master_Page.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class unlamEntities : DbContext
    {
        public unlamEntities()
            : base("name=unlamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Documento_Tipo> Documento_Tipo { get; set; }
        public DbSet<Estudiante> Estudiante { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<UsuarioLogin> UsuarioLogin { get; set; }
    }
}
